const BOT_UPLOAD_DAILY_LIMIT = process.env.BOT_UPLOAD_DAILY_LIMIT || 200000000; // ~200MB
const BOT_UPLOAD_FILE_TIME_LOCK =
  process.env.BOT_UPLOAD_FILE_TIME_LOCK || 10000;

module.exports = {
  BOT_UPLOAD_DAILY_LIMIT,
  BOT_UPLOAD_FILE_TIME_LOCK,
};
